### PR TITLE
Created another function to incorporate POST and GET requests

### PR DESCRIPTION
**Pull request by gracieorozco**
I accidentally committed a change to the wrong branch. This is supposed to be the POST() tutorial, which is the fourth pull request. 

I created a function within Java to receive information from a POST request and send back information for the GET requests. There are some layouts and formatting adjustments I would like to make before merging the branch with master. I posted this sooner for you to review the overall idea a bit sooner.

### CODE REVIEW

**Comment by KaylaNguyen** [comment]
Is this PR still active?

**Comment by gracieorozco** [comment]
This PR was supposed to be the fourth PR even though it says Week-2-PR-5. This code does not incorporate the data store found in the last part of the tutorial. Most of the code here is no longer used in the last part I believe. Once this is resolved, I plan to update the code to reflect the last pull request of week 2.

**Comment by KaylaNguyen** [comment]
Acked. Can you resolve conflicts for this PR and let me know when it's ready for review? Thanks! =)

**Comment by gracieorozco** [comment]
I've resolved the comments, and now it is ready for review.

**Comment by KaylaNguyen** [comment]
I only see 1 file change. If I understand this correctly, most of the change in this PR is already reflected in other submitted PRs? If so, do you still need this PR?

**Comment by gracieorozco** [comment]
It is, but I believe that merging this pull request is important since the walkthrough mentioned having my code reviewed.

**Pull request merged**
